version: '2'
services:
  indiserver:
    build:
      context: .
      dockerfile: Dockerfile-all.x86
    restart: always
    privileged: true
    volumes:
      - config:/root/.indi
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - 7624:7624

volumes:
  config:
