version: '2'
services:
  indiserver:
    build:
      context: .
      dockerfile: Dockerfile.x86
    restart: always
    privileged: true
    volumes:
      - config:/root/.indi
    ports:
      - 7624:7624

volumes:
  config:
