version: '2'
services:
  indiserver:
    image: seanhoughton/rpi-indiserver:1.3.1 # rpi
    command: indi_sbig_ccd indi_qhy_ccd indi_simulator_telescope indi_simulator_ccd
    restart: always
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/ttyUSB0:/dev/ttyUSB0
      - config:/root/.indi
    ports:
      - 7624:7624

volumes:
  config:
